driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  require_chef_omnubus: 11.16.4

platforms:
  - name: chef11
    driver:
      box: oel65-fixed
    provisioner:
      require_chef_omnubus: 11.16.4

suites:
  - name: default
    driver:
      vm_hostname: agent01
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[teamcity_agent_test::default]
    attributes:
      java:
         install_flavor: 'oracle'
         jdk_version: '8'
         oracle:
           accept_oracle_download_terms: true
      teamcity_agent:
        home: '/opt/elasticsearch_home'
        server_url: 'http://10.156.130.153:8111'    
        java:
          version: 'Oracle JDK 1.7u75'
          url: 'http://download.oracle.com/otn-pub/java/jdk/7u75-b13/jdk-7u75-linux-x64.tar.gz'
          pkg_checksum: '6f1f81030a34f7a9c987f8b68a24d139'
          home: '/opt/jdks/oracle-jdk7-x86_64'
