driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4
  environments_path: "test/integration/environments"
  client_rb:
    environment: localdev

platforms:
  - name: chef11
    driver:
      box: oel65-fixed
    provisioner:
      require_chef_omnibus: 11.16.4

suites:
  - name: default
    driver:
      vm_hostname: agent01
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[teamcity_agent_test::default]
    attributes:
